configuration: Release

# Don't build unless it's tagged
skip_non_tags: true

image:
  - Visual Studio 2019
  
cache:
  - packages -> **\packages.config

# Get the version from the tag name (strips v from the start)
init:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
          Update-AppveyorBuild -Version $env:APPVEYOR_REPO_TAG_NAME
      }

before_build:
  - git submodule update --init --recursive --remote
  - nuget restore "Concept Matrix.sln"
  
build:
  project: Concept Matrix.sln
    
after_build:
  7z a CMTool.zip %APPVEYOR_BUILD_FOLDER%\ConceptMatrix\bin\%CONFIGURATION%\*.exe %APPVEYOR_BUILD_FOLDER%\ConceptMatrix\bin\%CONFIGURATION%\*.txt %APPVEYOR_BUILD_FOLDER%\ConceptMatrix\bin\%CONFIGURATION%\OffsetSettings.json %APPVEYOR_BUILD_FOLDER%\ConceptMatrix\bin\%CONFIGURATION%\OffsetSettingsCN.json %APPVEYOR_BUILD_FOLDER%\ConceptMatrix\bin\%CONFIGURATION%\OffsetSettingsKO.json %APPVEYOR_BUILD_FOLDER%\ConceptMatrix\bin\%CONFIGURATION%\Definitions\ %APPVEYOR_BUILD_FOLDER%\ConceptMatrix\bin\%CONFIGURATION%\de\ %APPVEYOR_BUILD_FOLDER%\ConceptMatrix\bin\%CONFIGURATION%\fr\ %APPVEYOR_BUILD_FOLDER%\ConceptMatrix\bin\%CONFIGURATION%\zh\ %APPVEYOR_BUILD_FOLDER%\ConceptMatrix\bin\%CONFIGURATION%\ko\ %APPVEYOR_BUILD_FOLDER%\ConceptMatrix\bin\%CONFIGURATION%\ja\
    
artifacts:
  - path: CMTool.zip
    name: CMTool

deploy:
  tag: $(appveyor_repo_tag_name)
  release: Concept Matrix $(appveyor_repo_tag_name)
  provider: GitHub
  draft: true
  auth_token:
    secure: EAqDpXZoRTQ494m/Cxjf7IogaPI1fFxRATLxOUXugdVIgAgT26/GlJAKIlnJIGiV
  artifact: CMTool.zip
  on:
    branch: master
    appveyor_repo_tag: true
